### ISSUE TITLE
zui16.0.617 cann't edit file in TWRP.

### ISSUE THREAD

**Issue by kazegh** [lddnsk/android_device_lenovo_TB320FC#1]
Hello . I have tested this TWRP. I can't apply some changes for partition /data.(delete /data/cache/somelog;touch /data/adb/service.d/test.sh;rm /data/system/users/0/package-restrictions.xml. These changes will restore original state after reboot)

Can you please tell me why and help me to solve this problem?

**Comment by lddnsk** [comment]
Hi! 

> These changes will restore original state after reboot

You must check it after reboot recovery, not system.
I have been tested removing /data/cache/something and it work after rebooting twrp and after rebooting to system too.
Your system can replace this files from copy or generates new or you see the mirror of magisk binds or some other apps.
This is not problem of recovery. Check date and time of these files.
Also you can modify the files (not deleting) and place void content to it (echo "" > /data/cache/something) or try to set chmod 444 or 000.

Tell me what is your version of TWRP? I have tested on b0004-fix3

**Comment by kazegh** [comment]
> Hi!
> 
> > These changes will restore original state after reboot
> 
> You must check it after reboot recovery, not system. I have been tested removing /data/cache/something and it work after rebooting twrp and after rebooting to system too. Your system can replace this files from copy or generates new or you see the mirror of magisk binds or some other apps. This is not problem of recovery. Check date and time of these files. Also you can modify the files (not deleting) and place void content to it (echo "" > /data/cache/something) or try to set chmod 444 or 000.
> 
> Tell me what is your version of TWRP? I have tested on b0004-fix3

I have tested b0004-fix3 TWRP. I can't apply some changes for partition /data./sdcard (TWRP File Manager to delete & TWRP enable MTP connect USB to PC ,in PC to delete /scard/something;TWRP terminal : touch /data/adb/service.d/test.sh;rm /data/system/users/0/package-restrictions.xml. These changes will restore original state after reboot)
I cann't reboot to system because I disabled som system apps.
Can you tell me what is the possible reason?

**Comment by lddnsk** [comment]
I don't know what is this.
I tested this functions and it works correctly.
Maybe your root manager (magisk or apatch) have a mirror and after boot restores files from there.
You may to restore stock boot.img and try checking.
Also you can take a backup of data, then wipe. After first settings wizard are done you restore data from twrp.
System partition can be restored to stock via flashing super.img (take it from qfil rom).
